# file: .github/workflows/run-install-and-test.yml
name: run-install-and-test
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      with:
          node-version: 20
          cache: 'make'
      # run – произвольная bash-команда
      - run: make setup
      - run: make test
      - run: make lint
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
